import { User} from "../models/User";

export const mockUsers: User[] = [
    {
        _id: '1',
        name: 'John Doe',
        email: 'john@example.com',
        role: 'admin',
        status: 'active',
        createdAt: '2026-01-15T10:00:00Z',
    },
    {
        _id: '2',
        name: 'Jane Smith',
        email: 'jane@example.com',
        role: 'editor',
        status: 'active',
        createdAt: '2026-02-01T14:30:00Z',
    },
    {
        _id: '3',
        name: 'Bob Wilson',
        email: 'bob@example.com',
        role: 'viewer',
        status: 'inactive',
        createdAt: '2026-02-10T09:15:00Z',
    },
    {
        _id: '4',
        name: 'Alice Johnson',
        email: 'alice.j@example.com',
        role: 'admin',
        status: 'active',
        createdAt: '2026-02-12T08:00:00Z',
    },
    {
        _id: '5',
        name: 'Charlie Brown',
        email: 'charlie.b@example.com',
        role: 'viewer',
        status: 'active',
        createdAt: '2026-02-15T11:20:00Z',
    },
    {
        _id: '6',
        name: 'David Miller',
        email: 'd.miller@example.com',
        role: 'editor',
        status: 'inactive',
        createdAt: '2026-02-18T16:45:00Z',
    },
    {
        _id: '7',
        name: 'Eva Garcia',
        email: 'eva.g@example.com',
        role: 'viewer',
        status: 'active',
        createdAt: '2026-02-20T10:30:00Z',
    },
    {
        _id: '8',
        name: 'Frank Wright',
        email: 'frank.w@example.com',
        role: 'admin',
        status: 'inactive',
        createdAt: '2026-02-22T13:10:00Z',
    },
    {
        _id: '9',
        name: 'Grace Lee',
        email: 'grace.l@example.com',
        role: 'editor',
        status: 'active',
        createdAt: '2026-02-25T09:05:00Z',
    },
    {
        _id: '10',
        name: 'Henry Adams',
        email: 'henry.a@example.com',
        role: 'viewer',
        status: 'active',
        createdAt: '2026-02-28T14:50:00Z',
    },
    {
        _id: '11',
        name: 'Isabel Chen',
        email: 'isabel.c@example.com',
        role: 'editor',
        status: 'active',
        createdAt: '2026-03-01T12:00:00Z',
    },
    {
        _id: '12',
        name: 'Jack Ross',
        email: 'jack.r@example.com',
        role: 'viewer',
        status: 'inactive',
        createdAt: '2026-03-02T08:30:00Z',
    },
];